{{- define "cloud-provider-disk-config" -}}
[Global]
{{ include "cloud-provider-config-credentials" . }}
{{ include "cloud-provider-config-meta" . }}
{{- if semverCompare ">= 1.19-0" .Values.kubernetesVersion }}
[BlockStorage]
rescan-on-resize={{ .Values.rescanBlockStorageOnResize }}
{{- end }}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-provider-disk-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cloudprovider.conf: {{ include "cloud-provider-disk-config" . | b64enc }}
